version: "3"
services:
  springboot-app:
    container_name: devops-project
    image: mtar/devops-project
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ./my-datavolume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network

  frontend:
    image: mtar/angular-app:latest
    container_name: angular
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    restart: unless-stopped
    depends_on:
      - springboot-app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge